# `pandas`

Basically, each Python library defines one or more **core classes** that represent its core functionality, along with additional utility functions that support or extend those core features. 

Let’s take a closer look at the `pandas` library from this point of view.

**Core classes**
- `Index`: Class that labels rows or columns
- `Series`: 1D labeled array
- `DataFrame`: 2D labeled array

More specifically, the class hierarchy in pandas can be summarized as follows:

```text
NDFrame: collection of data
 ├── Series: 1D array
 └── DataFrame: 2D array (two Index classes (row/column) and multiple Series classes)

 Index: labels used to identify rows or columns
 ├── RangeIndex
 ├── DatetimeIndex
 ├── MultiIndex
 └── ...
 ```

In [107]:
import pandas as pd

## Core Classes
### `Series`

In [108]:
s = pd.Series(data = [10, 7, 15, 6, 8, None], 
              index = ['a', 'b', 'c', 'd', 'e', 'f'])

In [109]:
s

a    10.0
b     7.0
c    15.0
d     6.0
e     8.0
f     NaN
dtype: float64

In [110]:
print(type(s))

<class 'pandas.Series'>

In [111]:
print(s.index)
print(type(s.index))

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='str')
<class 'pandas.Index'>

In [112]:
print(s.values)
print(type(s.values))

[10.  7. 15.  6.  8. nan]
<class 'numpy.ndarray'>

### `DataFrame`

In [113]:
sales = pd.DataFrame({
    "date": ["2024-01-05", "2024-01-07", "2024-01-10", "2024-02-02", "2024-02-05", "2024-02-10"],
    "region": ["East", "West", "East", "South", "West", "East"],
    "product": ["B", "A", "B", "B", "A", "B"],
    "units": [10, 6, 15, 6, 8, None],
    "price": [2.50, 3.00, 4.00, 4.00, None, 4.50],
    "returned": [False, False, True, False, False, True]
})

In [114]:
print(type(sales))

<class 'pandas.DataFrame'>

In [115]:
sales_idx = sales.index
sales_col = sales.columns
sales_values = sales.values

In [116]:
print(sales_idx)
print(type(sales_idx))

RangeIndex(start=0, stop=6, step=1)
<class 'pandas.RangeIndex'>

In [117]:
print(sales_col)
print(type(sales_col))

Index(['date', 'region', 'product', 'units', 'price', 'returned'], dtype='str')
<class 'pandas.Index'>

In [118]:
print(sales_values)
print(type(sales_values))

[['2024-01-05' 'East' 'B' 10.0 2.5 False]
 ['2024-01-07' 'West' 'A' 6.0 3.0 False]
 ['2024-01-10' 'East' 'B' 15.0 4.0 True]
 ['2024-02-02' 'South' 'B' 6.0 4.0 False]
 ['2024-02-05' 'West' 'A' 8.0 nan False]
 ['2024-02-10' 'East' 'B' nan 4.5 True]]
<class 'numpy.ndarray'>

## Attributes and methods of `DataFrame`

### Attributes

In [119]:
sales.shape # shape of the DataFrame

(6, 6)

In [120]:
sales.size # number of elements in the DataFrame

36

In [121]:
sales.dtypes # data types of each column

date            str
region          str
product         str
units       float64
price       float64
returned       bool
dtype: object

In [122]:
sales.T # transpose rows and columns

,0,1,2,3,4,5
date,2024-01-05,2024-01-07,2024-01-10,2024-02-02,2024-02-05,2024-02-10
region,East,West,East,South,West,East
product,B,A,B,B,A,B
units,10.0,6.0,15.0,6.0,8.0,NaN
price,2.5,3.0,4.0,4.0,NaN,4.5
returned,False,False,True,False,False,True

### Methods

#### Data inspection / preview / summary methods

These methods help us quickly check what the data looks like before analysis.

In [123]:
sales.head() # preview the first 5 rows

         date region product  units  price  returned
0  2024-01-05   East       B   10.0    2.5     False
1  2024-01-07   West       A    6.0    3.0     False
2  2024-01-10   East       B   15.0    4.0      True
3  2024-02-02  South       B    6.0    4.0     False
4  2024-02-05   West       A    8.0    NaN     False

In [124]:
sales.tail(1) # preview the last 1 row

         date region product  units  price  returned
5  2024-02-10   East       B    NaN    4.5      True

In [125]:
sales.sample(2, random_state=1) # random sample of rows

         date region product  units  price  returned
2  2024-01-10   East       B   15.0    4.0      True
1  2024-01-07   West       A    6.0    3.0     False

In [126]:
sales.info() # concise summary of columns, non-null values, and data types

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      6 non-null      str
 1   region    6 non-null      str
 2   product   6 non-null      str
 3   units     5 non-null      float64
 4   price     5 non-null      float64
 5   returned  6 non-null      bool
dtypes: bool(1), float64(2), str(3)
memory usage: 378.0 bytes

In [127]:
sales.describe() # summary statistics

           units     price
count   5.000000  5.000000
mean    9.000000  3.600000
std     3.741657  0.821584
min     6.000000  2.500000
25%     6.000000  3.000000
50%     8.000000  4.000000
75%    10.000000  4.000000
max    15.000000  4.500000

#### Indexing: selecting by label and position

- `.loc[row_labels, column_labels]` selects by index/column labels.
- `.iloc[row_positions, column_positions]` selects by integer positions.

In [128]:
sales.loc[0] # selecting a single row by index label
## This returns a Series, not a DataFrame.

date        2024-01-05
region            East
product              B
units             10.0
price              2.5
returned         False
Name: 0, dtype: object

In [129]:
sales.loc[[0]] # This returns a DataFrame, not a Series.

         date region product  units  price  returned
0  2024-01-05   East       B   10.0    2.5     False

In [130]:
sales.loc[:, "region"] # selecting a single column by label
## This returns a Series, not a DataFrame.

0     East
1     West
2     East
3    South
4     West
5     East
Name: region, dtype: str

In [131]:
sales.loc[:, ["region"]] # This returns a DataFrame, not a Series.

  region
0   East
1   West
2   East
3  South
4   West
5   East

In [132]:
sales.loc[[0,1,2]] # selecting multiple rows by index label

         date region product  units  price  returned
0  2024-01-05   East       B   10.0    2.5     False
1  2024-01-07   West       A    6.0    3.0     False
2  2024-01-10   East       B   15.0    4.0      True

In [133]:
sales.loc[0:2]

         date region product  units  price  returned
0  2024-01-05   East       B   10.0    2.5     False
1  2024-01-07   West       A    6.0    3.0     False
2  2024-01-10   East       B   15.0    4.0      True

In [134]:
sales.loc[:, ["region", "units"]] # selecting multiple columns by label

  region  units
0   East   10.0
1   West    6.0
2   East   15.0
3  South    6.0
4   West    8.0
5   East    NaN

In [135]:
sales.loc[0:2, ["region", "units"]]

  region  units
0   East   10.0
1   West    6.0
2   East   15.0

In [136]:
sales.loc[[0,2,4], ["region", "units"]]

  region  units
0   East   10.0
2   East   15.0
4   West    8.0

In [137]:
sales.iloc[0:3, [0, 2, 3]]

         date product  units
0  2024-01-05       B   10.0
1  2024-01-07       A    6.0
2  2024-01-10       B   15.0

#### Index
`set_index()`:
`reset_index()`:

In [138]:
sales.set_index("date") 
# This returns a new DataFrame with the "date" column as the index, but does not modify the original DataFrame.

           region product  units  price  returned
date
2024-01-05   East       B   10.0    2.5     False
2024-01-07   West       A    6.0    3.0     False
2024-01-10   East       B   15.0    4.0      True
2024-02-02  South       B    6.0    4.0     False
2024-02-05   West       A    8.0    NaN     False
2024-02-10   East       B    NaN    4.5      True

In [139]:
sales_by_date = sales.set_index("date")
sales_by_date

           region product  units  price  returned
date
2024-01-05   East       B   10.0    2.5     False
2024-01-07   West       A    6.0    3.0     False
2024-01-10   East       B   15.0    4.0      True
2024-02-02  South       B    6.0    4.0     False
2024-02-05   West       A    8.0    NaN     False
2024-02-10   East       B    NaN    4.5      True

In [140]:
sales_by_date.index

Index(['2024-01-05', '2024-01-07', '2024-01-10', '2024-02-02', '2024-02-05',
       '2024-02-10'],
      dtype='str', name='date')

In [141]:
sales_by_date.loc["2024-01"] # Can I select rows by a partial date string (e.g. YYYY-MM)?

KeyError: '2024-01'

In [ ]:
# You can do that if the index is in datetime format.
sales_by_date.index = pd.to_datetime(sales_by_date.index) # Convert the index to datetime format
sales_by_date.index

DatetimeIndex(['2024-01-05', '2024-01-07', '2024-01-10', '2024-02-02',
               '2024-02-05', '2024-02-10'],
              dtype='datetime64[us]', name='date', freq=None)

In [ ]:
sales_by_date.loc["2024-01"] # selecting rows by index label (date range)

           region product  units  price  returned
date
2024-01-05   East       B   10.0    2.5     False
2024-01-07   West       A    6.0    3.0     False
2024-01-10   East       B   15.0    4.0      True

In [ ]:
sales_by_date.reset_index() # resetting the index. 
## Note that this method returns a new DataFrame and does not modify the original DataFrame in place.

        date region product  units  price  returned
0 2024-01-05   East       B   10.0    2.5     False
1 2024-01-07   West       A    6.0    3.0     False
2 2024-01-10   East       B   15.0    4.0      True
3 2024-02-02  South       B    6.0    4.0     False
4 2024-02-05   West       A    8.0    NaN     False
5 2024-02-10   East       B    NaN    4.5      True

In [ ]:
sales_by_date

           region product  units  price  returned
date
2024-01-05   East       B   10.0    2.5     False
2024-01-07   West       A    6.0    3.0     False
2024-01-10   East       B   15.0    4.0      True
2024-02-02  South       B    6.0    4.0     False
2024-02-05   West       A    8.0    NaN     False
2024-02-10   East       B    NaN    4.5      True

#### Subsetting: filtering rows and choosing columns

Use column lists for columns, boolean conditions for rows.

In [ ]:
sales["region"] # selecting a single column by label

0     East
1     West
2     East
3    South
4     West
5     East
Name: region, dtype: str

In [ ]:
sales[["region", "product", "units"]] # selecting multiple columns by label

  region product  units
0   East       B   10.0
1   West       A    6.0
2   East       B   15.0
3  South       B    6.0
4   West       A    8.0
5   East       B    NaN

In [ ]:
sales[sales["units"] >= 10] # filtering rows based on a condition

         date region product  units  price  returned
0  2024-01-05   East       B   10.0    2.5     False
2  2024-01-10   East       B   15.0    4.0      True

In [ ]:
mask = (sales["region"] == "East") & (sales["units"] >= 10) # creating a boolean mask for filtering rows
mask

0     True
1    False
2     True
3    False
4    False
5    False
dtype: bool

In [ ]:
sales[mask] # filtering rows using the boolean mask

In [ ]:
sales.loc[mask, ["date", "region", "units"]] # filtering rows using the boolean mask and selecting specific columns

#### Sorting methods

`sort_values()` sorts all rows.

In [ ]:
sales.sort_values("units", ascending=False) # sort by one column

In [ ]:
sales.sort_values(["units", "price"], ascending=[True, False]) # sort by multiple columns

### Value counts
`value_counts()` returns eqch unique value and its count.

In [ ]:
sales["product"].value_counts() # count occurrences of each unique value in a column

In [ ]:
sales["region"].value_counts(ascending=False)

In [ ]:
sales[["region", "product"]].value_counts()

#### Column operations

Common column operations include creating new columns, deleting columns, renaming columns, and changing data types.

In [144]:
sales["revenue"] = sales["units"] * sales["price"] # adding a new column with []
# This method directly modifies the DataFrame in place and does not return a new DataFrame.

In [143]:
sales

         date region product  units  price  returned
0  2024-01-05   East       B   10.0    2.5     False
1  2024-01-07   West       A    6.0    3.0     False
2  2024-01-10   East       B   15.0    4.0      True
3  2024-02-02  South       B    6.0    4.0     False
4  2024-02-05   West       A    8.0    NaN     False
5  2024-02-10   East       B    NaN    4.5      True

In [142]:
sales.drop(columns=["returned"]) # deleting columns
# This method returns a new DataFrame and does not modify the original DataFrame in place.

         date region product  units  price
0  2024-01-05   East       B   10.0    2.5
1  2024-01-07   West       A    6.0    3.0
2  2024-01-10   East       B   15.0    4.0
3  2024-02-02  South       B    6.0    4.0
4  2024-02-05   West       A    8.0    NaN
5  2024-02-10   East       B    NaN    4.5

In [145]:
sales.rename(columns={"region": "sales_region", "units": "units_sold"}) # renaming columns
# This method returns a new DataFrame and does not modify the original DataFrame in place.

         date sales_region product  units_sold  price  returned  revenue
0  2024-01-05         East       B        10.0    2.5     False     25.0
1  2024-01-07         West       A         6.0    3.0     False     18.0
2  2024-01-10         East       B        15.0    4.0      True     60.0
3  2024-02-02        South       B         6.0    4.0     False     24.0
4  2024-02-05         West       A         8.0    NaN     False      NaN
5  2024-02-10         East       B         NaN    4.5      True      NaN

In [146]:
sales.astype({"region": "category", "product": "category", "units": "Int64"}) # changing data types of columns
# This method returns a new DataFrame and does not modify the original DataFrame in place.

         date region product  units  price  returned  revenue
0  2024-01-05   East       B     10    2.5     False     25.0
1  2024-01-07   West       A      6    3.0     False     18.0
2  2024-01-10   East       B     15    4.0      True     60.0
3  2024-02-02  South       B      6    4.0     False     24.0
4  2024-02-05   West       A      8    NaN     False      NaN
5  2024-02-10   East       B   <NA>    4.5      True      NaN

#### Writing data

In [148]:
# sales.to_csv("sales_data.csv", index=False) # saving the DataFrame to a CSV file
## CSV files do not preserve data type information.
## When reading a CSV file back into a DataFrame by `pd.read_csv()`, pandas will "infer" the appropriate data types for each column.

`to_markdown()` method returns a string representation of a DataFrame formatted as a Markdown table. 

This is useful when you want to display a DataFrame inside a Markdown document. 
- Copy the output and paste it into your `.md` file. 
- When you copy the output, it will look like `'| ... |\n| ...|'`. Remove the quotes at both ends, then replace every `\n` with an actual line break.
- You need `tabulate` package for this. Add it by using `uv sync`.

In [150]:
sales.to_markdown()

'|    | date       | region   | product   |   units |   price | returned   |   revenue |\n|---:|:-----------|:---------|:----------|--------:|--------:|:-----------|----------:|\n|  0 | 2024-01-05 | East     | B         |      10 |     2.5 | False      |        25 |\n|  1 | 2024-01-07 | West     | A         |       6 |     3   | False      |        18 |\n|  2 | 2024-01-10 | East     | B         |      15 |     4   | True       |        60 |\n|  3 | 2024-02-02 | South    | B         |       6 |     4   | False      |        24 |\n|  4 | 2024-02-05 | West     | A         |       8 |   nan   | False      |       nan |\n|  5 | 2024-02-10 | East     | B         |     nan |     4.5 | True       |       nan |'

You don’t need to memorize everything (I mean you **CAN'T**)! What truly matters is learning:
- how to search for the commands you need
- how to understand the documentation
- how to handle errors.